import { readFileSync } from "node:fs";
import path from "node:path";
import { cacheLife } from "next/cache";
import { codeToHtml } from "shiki";

// Renders the lesson's own source files, highlighted on the server (no client JS).
export default function Source({ files }: { files: string[] }) {
  return files.map((file) => {
    // Sync file reads are allowed during prerendering.
    const code = readFileSync(
      path.join(/*turbopackIgnore: true*/ process.cwd(), file),
      "utf8",
    );
    return (
      <figure key={file} className="source">
        <figcaption>{file}</figcaption>
        <Highlighted code={code} />
      </figure>
    );
  });
}

// Shiki is async and reads the clock internally, so its output is cached.
// The code itself is the cache key: edit a file and it re-highlights.
async function Highlighted({ code }: { code: string }) {
  "use cache";
  cacheLife("max");
  const html = await codeToHtml(code, {
    lang: "tsx",
    themes: { light: "github-light", dark: "vesper" },
    defaultColor: false, // Only CSS variables; globals.css picks light or dark.
  });
  // Safe: the HTML is generated by shiki from our own files.
  return <div dangerouslySetInnerHTML={{ __html: html }} />;
}
